### ISSUE TITLE
New URL format + URL sign = crash (in some cases)

### ISSUE THREAD

**Issue by afitiskin** [DarthSim/imgproxy#82]
Source image: https://dev-swm.s3.eu-central-1.amazonaws.com/suk4sWJp9PenLBOxlemHKcA6ygFTqzsS1lRfkDzr/1526250326_original.jpeg

Resize params:
* `gravity:sm`
* `blur:10`
* `resize:fill:300:300:1`
* `extension:jpeg`

2 imgproxy instances, one with salt+key and one without, see `docker-compose.yml`:

```yaml
version: '3'
services:
  imgproxy1:
    container_name: 'imgproxy1'
    image: 'darthsim/imgproxy'
    restart: always
    environment:
      - IMGPROXY_KEY=1292938475674739305069685674636525623743845956067079685847476365
      - IMGPROXY_SALT=0595984873723626373848459596060769689585746736263738484595956069
    ports:
      - '8081:8080'
  imgproxy2:
    container_name: 'imgproxy2'
    image: 'darthsim/imgproxy'
    restart: always
    ports:
      - '8082:8080'
```

Result image URLs:
```
http://127.0.0.1:8081/cZgEylho58Fc-TCYof7WVl_q-thotejPuEa9SD1CrRo/gravity:sm/blur:10/resize:fill:300:300:1/aHR0cHM6Ly9kZXYtc3dtLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3N1azRzV0pwOVBlbkxCT3hsZW1IS2NBNnlnRlRxenNTMWxSZmtEenIvMTUyNjI1MDMyNl9vcmlnaW5hbC5qcGVn.jpeg
http://127.0.0.1:8082/gravity:sm/blur:10/resize:fill:300:300:1/aHR0cHM6Ly9kZXYtc3dtLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3N1azRzV0pwOVBlbkxCT3hsZW1IS2NBNnlnRlRxenNTMWxSZmtEenIvMTUyNjI1MDMyNl9vcmlnaW5hbC5qcGVn.jpeg
```

Second one (without URL signature) works fine, first one (with URL signature) respond with nothing. In docker-compose logs I see following:

```
imgproxy1    | 2018/10/25 10:26:27 [9EvE95M6cCB_WdnnOiQ4UC] GET: /cZgEylho58Fc-TCYof7WVl_q-thotejPuEa9SD1CrRo/gravity:sm/blur:10/resize:fill:300:300:1/aHR0cHM6Ly9kZXYtc3dtLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3N1azRzV0pwOVBlbkxCT3hsZW1IS2NBNnlnRlRxenNTMWxSZmtEenIvMTUyNjI1MDMyNl9vcmlnaW5hbC5qcGVn.jpeg
imgproxy1 exited with code 139
imgproxy1    | 2018/10/25 10:19:03 Starting server at :8080
imgproxy1    | 2018/10/25 10:19:36 [l1zeFcC9EGbuF9Yt7JJnqs] GET: /cZgEylho58Fc-TCYof7WVl_q-thotejPuEa9SD1CrRo/gravity:sm/blur:10/resize:fill:300:300:1/aHR0cHM6Ly9kZXYtc3dtLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3N1azRzV0pwOVBlbkxCT3hsZW1IS2NBNnlnRlRxenNTMWxSZmtEenIvMTUyNjI1MDMyNl9vcmlnaW5hbC5qcGVn.jpeg
imgproxy1    | 2018/10/25 10:19:39 Starting server at :8080
imgproxy1    | 2018/10/25 10:19:42 [5r_zZfnXuewUTk2QxYXG9q] GET: /cZgEylho58Fc-TCYof7WVl_q-thotejPuEa9SD1CrRo/gravity:sm/blur:10/resize:fill:300:300:1/aHR0cHM6Ly9kZXYtc3dtLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3N1azRzV0pwOVBlbkxCT3hsZW1IS2NBNnlnRlRxenNTMWxSZmtEenIvMTUyNjI1MDMyNl9vcmlnaW5hbC5qcGVn.jpeg
imgproxy1    | 2018/10/25 10:19:45 Starting server at :8080
imgproxy1    | 2018/10/25 10:25:54 [DxxixYB_ejsVTxt3fXGW4h] GET: /cZgEylho58Fc-TCYof7WVl_q-thotejPuEa9SD1CrRo/gravity:sm/blur:10/resize:fill:300:300:1/aHR0cHM6Ly9kZXYtc3dtLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3N1azRzV0pwOVBlbkxCT3hsZW1IS2NBNnlnRlRxenNTMWxSZmtEenIvMTUyNjI1MDMyNl9vcmlnaW5hbC5qcGVn.jpeg
imgproxy1    | 2018/10/25 10:25:57 Starting server at :8080
imgproxy1    | 2018/10/25 10:26:07 [1_GrefIqdwBQzlr6rkpiBw] GET: /cZgEylho58Fc-TCYof7WVl_q-thotejPuEa9SD1CrRo/gravity:sm/blur:10/resize:fill:300:300:1/aHR0cHM6Ly9kZXYtc3dtLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3N1azRzV0pwOVBlbkxCT3hsZW1IS2NBNnlnRlRxenNTMWxSZmtEenIvMTUyNjI1MDMyNl9vcmlnaW5hbC5qcGVn.jpeg
imgproxy1    | 2018/10/25 10:26:10 Starting server at :8080
imgproxy1    | 2018/10/25 10:26:27 [9EvE95M6cCB_WdnnOiQ4UC] GET: /cZgEylho58Fc-TCYof7WVl_q-thotejPuEa9SD1CrRo/gravity:sm/blur:10/resize:fill:300:300:1/aHR0cHM6Ly9kZXYtc3dtLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3N1azRzV0pwOVBlbkxCT3hsZW1IS2NBNnlnRlRxenNTMWxSZmtEenIvMTUyNjI1MDMyNl9vcmlnaW5hbC5qcGVn.jpeg
imgproxy1    | 2018/10/25 10:26:30 Starting server at :8080
imgproxy1    | 2018/10/25 10:26:34 [Q7W0j9ewL~ArrPzx1Trup~] GET: /cZgEylho58Fc-TCYof7WVl_q-thotejPuEa9SD1CrRo/gravity:sm/blur:10/resize:fill:300:300:1/aHR0cHM6Ly9kZXYtc3dtLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3N1azRzV0pwOVBlbkxCT3hsZW1IS2NBNnlnRlRxenNTMWxSZmtEenIvMTUyNjI1MDMyNl9vcmlnaW5hbC5qcGVn.jpeg
imgproxy1    | 2018/10/25 10:26:37 Starting server at :8080
```

PS. I experienced problems with various images and various params. But most of the pictures are processed normally
